// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzrxOC67JEW0FhWAX46UwJVExtLpoyDZo',
    appId: '1:725932365866:web:d4c5d42db9443c82a58b53',
    messagingSenderId: '725932365866',
    projectId: 'personal-planer-f802e',
    authDomain: 'personal-planer-f802e.firebaseapp.com',
    storageBucket: 'personal-planer-f802e.appspot.com',
    measurementId: 'G-F9CKV06X5M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrCLeRXQZv2wCicVEJV6riupFt9f4moVA',
    appId: '1:725932365866:android:48a39d395e5b5fdaa58b53',
    messagingSenderId: '725932365866',
    projectId: 'personal-planer-f802e',
    storageBucket: 'personal-planer-f802e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0bNb0yR8ObeVc0RqPNzw7PzN667nOu2E',
    appId: '1:725932365866:ios:99d6a73e8110fce3a58b53',
    messagingSenderId: '725932365866',
    projectId: 'personal-planer-f802e',
    storageBucket: 'personal-planer-f802e.appspot.com',
    iosBundleId: 'com.example.personalPlannerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0bNb0yR8ObeVc0RqPNzw7PzN667nOu2E',
    appId: '1:725932365866:ios:99d6a73e8110fce3a58b53',
    messagingSenderId: '725932365866',
    projectId: 'personal-planer-f802e',
    storageBucket: 'personal-planer-f802e.appspot.com',
    iosBundleId: 'com.example.personalPlannerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzrxOC67JEW0FhWAX46UwJVExtLpoyDZo',
    appId: '1:725932365866:web:12a8066475d98602a58b53',
    messagingSenderId: '725932365866',
    projectId: 'personal-planer-f802e',
    authDomain: 'personal-planer-f802e.firebaseapp.com',
    storageBucket: 'personal-planer-f802e.appspot.com',
    measurementId: 'G-RP05NNHHZR',
  );
}
